
-- DROP TABLE IF EXISTS entidades;

CREATE TABLE IF NOT EXISTS Entidades(
    CO_ENTIDADE INTEGER PRIMARY KEY,
    NO_ENTIDADE TEXT NOT NULL,
    CO_UF INTEGER NOT NULL,
    CO_MUNICIPIO INTEGER NOT NULL,
    CO_MESORREGIAO INTEGER NOT NULL,
    CO_MICRORREGIAO INTEGER NOT NULL,
    QT_MAT_BAS INTEGER,
    QT_MAT_INF INTEGER,
    QT_MAT_FUND INTEGER,
    QT_MAT_MED INTEGER,
    QT_MAT_MED_CT INTEGER,
    QT_MAT_MED_NM INTEGER,
    QT_MAT_PROF INTEGER,
    QT_MAT_PROF_TEC INTEGER,
    QT_MAT_EJA INTEGER,
    QT_MAT_ESP INTEGER,
    FOREIGN KEY (CO_UF) REFERENCES UF(CO_UF),
    FOREIGN KEY(CO_MUNICIPIO) REFERENCES MUNICIPIO(CO_MUNICIPIO),
    FOREIGN KEY (CO_MESORREGIAO) REFERENCES MESORREGIAO(CO_MESORREGIAO),
    FOREIGN KEY (CO_MICRORREGIAO) REFERENCES MICRORREGIAO(CO_MICRORREGIAO)


);
